-- 테이블 생성 SQL - TB_BOARD
CREATE TABLE TB_BOARD
(
    BOARD_ID       NUMBER           NULL,
    TITLE          VARCHAR2(200)    NOT NULL,
    CONTENT        CLOB             NULL,
    WRITER         VARCHAR2(50)     NOT NULL,
    REG_DATE       DATE             DEFAULT SYSDATE NULL,
    VIEW_COUNT     NUMBER           DEFAULT 0 NULL,
    REPLY_COUNT    NUMBER           DEFAULT 0 NULL,
    PRIMARY KEY (BOARD_ID)
);

-- 테이블 Comment 설정 SQL - TB_BOARD
COMMENT ON TABLE TB_BOARD IS '게시판. 게시판';

-- 컬럼 Comment 설정 SQL - TB_BOARD.BOARD_ID
COMMENT ON COLUMN TB_BOARD.BOARD_ID IS '게시글 번호. 게시글 번호';

-- 컬럼 Comment 설정 SQL - TB_BOARD.TITLE
COMMENT ON COLUMN TB_BOARD.TITLE IS '제목. 제목';

-- 컬럼 Comment 설정 SQL - TB_BOARD.CONTENT
COMMENT ON COLUMN TB_BOARD.CONTENT IS '내용. 내용';

-- 컬럼 Comment 설정 SQL - TB_BOARD.WRITER
COMMENT ON COLUMN TB_BOARD.WRITER IS '작성자. 작성자';

-- 컬럼 Comment 설정 SQL - TB_BOARD.REG_DATE
COMMENT ON COLUMN TB_BOARD.REG_DATE IS '작성일. 작성일';

-- 컬럼 Comment 설정 SQL - TB_BOARD.VIEW_COUNT
COMMENT ON COLUMN TB_BOARD.VIEW_COUNT IS '조회수. 조회수';

-- 컬럼 Comment 설정 SQL - TB_BOARD.REPLY_COUNT
COMMENT ON COLUMN TB_BOARD.REPLY_COUNT IS '댓글수. 댓글수';

-- Index 설정 SQL - TB_BOARD(REG_DATE)
CREATE INDEX IDX_BOARD_REGDATE
    ON TB_BOARD(REG_DATE);

-- Index 설정 SQL - TB_BOARD(TITLE)
CREATE INDEX IDX_BOARD_TITLE
    ON TB_BOARD(TITLE);

-- Index 설정 SQL - TB_BOARD(WRITER)
CREATE INDEX IDX_BOARD_WRITER
    ON TB_BOARD(WRITER);

